# Generated by Django 3.2.7 on 2022-01-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WA', 'Waiting'), ('DE', 'Delivered'), ('PD', 'Partially Delivered'), ('PP', 'Preparing'), ('CA', 'Canceled'), ('PA', 'Paid')], default='WA', max_length=100),
        ),
    ]
