# Generated by Django 3.2.7 on 2022-01-20 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220120_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.payments'),
        ),
    ]
